### ISSUE TITLE
AJV version and configuration

### ISSUE THREAD

**Issue by spasquali-ww** [cdimascio/express-openapi-validator#582] opened 2021-04-14 17:20 UTC
Love this project. Using it extensively. 

One application using it uses AJV elsewhere in the stack. For that part of the stack I'm using the latest version of AJV (8).

It seems like EOV uses AJV 6. That's fine, but wondering if a version upgrade is possible. Selfishly, I'd like to have version parity across my app.

Additionally I'd like to be able to have control over the AJV configuration used by EOV. I may have missed it but don't see where I can control the formats, keywords, and general options for AJV.

Also, would like to know/control the JSONSchema draft specification that is being supported (say, Draft 07)

Thanks!

**Comment by cdimascio** [comment] 2021-04-18 03:34
thanks @spasquali-ww, im closing this as it is effectively a duplicate of #573. moving to the latest AJV means upgrading json schema

**Closed by cdimascio** 2021-04-18 03:34 UTC
