### ISSUE TITLE
String type validation is not adhered to request validation

### ISSUE THREAD

**Issue by Jakesterwars** [cdimascio/express-openapi-validator#328] opened 2020-07-07 03:16 UTC
**Describe the bug**
When using a string type, passing in a number or integer value it does not invalidate the request coming in.

**To Reproduce**
Run the 1-standard example in the examples directory and hit `http://localhost:3000/v1/pets` with the body 
`{
    "name": 123,
    "type": "dog"
}`

A heads up you will need to change the post function to use .create instead of .add since that does not exist. I'm opening a PR for that separately to fix the example.

**Actual behavior** 
A successful addition to the pets list.

**Expected behavior**
Request fails due to validation error on string type due to number/integer passed in body.

**Comment by cdimascio** [comment] 2020-07-07 23:15
@Jakesterwars this is a duplicate of https://github.com/cdimascio/express-openapi-validator/issues/249. I'd looking for help on it. If u r interested, I've outlined a number of hints in the linked issue. Let me know if you are interested in taking a go at it

**Comment by cdimascio** [comment] 2020-07-07 23:16
Closing dup if #249

**Closed by cdimascio** 2020-07-07 23:16 UTC
