### ISSUE TITLE
Stop using openapi-* dependencies 

### ISSUE THREAD

**Issue by sheldhur** [cdimascio/express-openapi-validator#14] opened 2019-07-14 13:19 UTC
Why? 

`openapi-request-coercer` - `Ajv` can do it
`openapi-default-setter` - `Ajv` can do it
`openapi-request-validator` -  it's wrapper over `Ajv` that can't correctly resolve $ref. But `Ajv` no have troubles with resolving $ref

**Comment by cdimascio** [comment] 2019-07-15 14:08
@sheldhur thanks for the recommendation. this is a great idea to remove the dep on openapi-request-validator. I will look into this. 
please let me know, if already have some suggestions. if so, please post them here or create a PR.
thanks so much for helping to improve this package!

**Comment by sheldhur** [comment] 2019-07-15 14:57
@cdimascio I made this implementation, you can take this as a basis
https://gist.github.com/sheldhur/5111f3afee51de6698dfc626d65f95c5

**Comment by cdimascio** [comment] 2019-07-17 13:06
@sheldhur much appreciated! i will have a look at this and work to remove the dependency. if you have something working feel free to submit a PR. i'll gladly merge if it looks good. 
again, thanks for your help!

**Comment by cdimascio** [comment] 2019-07-17 20:17
@sheldhur, i've added much of your validator gist into the branch `req_validator`. It's not working yet and most tests fail. In any case, I did want to at least get the bulk of your code in there, so that I can experiment with it. Feel free to contribute as well.

**Comment by cdimascio** [comment] 2019-07-17 20:24
diff is [here](https://github.com/cdimascio/express-openapi-validator/compare/req_validator?expand=1)

**Comment by cdimascio** [comment] 2019-07-18 01:08
made a bit of progress this evening WITH @sheldhur's validator

```
  28 passing (292ms)
  18 failing
```

**Comment by sheldhur** [comment] 2019-07-19 04:08
@cdimascio my code support only `application/json` content-type in request body. You can try change 
`schema.content[TYPE_JSON].schema` 
on 
`schema.content[TYPE_JSON].schema || schema.content[TYPE_FORM].schema` 
in initAjv for support `multipart/form-data`. But it not will work with several content types request body schema. If it is critical, I will try to fix it on the weekend

https://github.com/cdimascio/express-openapi-validator/blob/e934e372e9aab4deafaa2d3223cd1cb161848e44/src/middlewares/openapi.request.validator.2.ts#L97

**Comment by cdimascio** [comment] 2019-07-19 15:51
That would be fantastic

**Comment by cdimascio** [comment] 2019-07-19 15:54
@sheldhur  There appears to be an issue with request bodies. 

For example, if you run the test below you'll see that the body is not being validated by Ajv. 
```
      it.only('should return 400 if required "name" property is missing', async () =>
        request(app)
          .post(`${basePath}/pets`)
          .send({})
          .expect(400)
          .then(r => {
            const e = r.body.errors;
            expect(e[0].message).to.equal(
              "should have required property 'name'",
            );
          }));
```

I think the issue is related to how the body is represented in the schema passed to Ajv. There is likely some work to do here:

```
   let body = pathSchema.requestBody || {};

    const schema = {
      // $schema: "http://json-schema.org/draft-04/schema#",
      required: ['query', 'headers', 'params'],
      properties: {
        body,
        ...parameters.schema,
      },
    };
```

I'm poking at this, however if you have some thoughts or have a fix on hand, I'd greatly appreciate it

**Comment by cdimascio** [comment] 2019-07-19 15:57
FYI, if you use VSCode, you can enable the debugger on the mocha tests with the following `launch.json`

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha All",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "-r",
                "ts-node/register",
                "--timeout",
                "999999",
                "--colors",
                "${workspaceFolder}/test/**/*.spec.ts",
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "protocol": "inspector"
        }
]
```

**Comment by sheldhur** [comment] 2019-07-19 16:24
> There is likely some work to do here

@cdimascio Yeap. I don't understand why it's not work in your test. For example `/pets/my_id` in tests return what the `id` is not defined, but when I check it on my project all it's ok: `should be integer`. I think It may be because you modify `req` before validate. 

Structure `req` must be equivalent for created schema in https://github.com/cdimascio/express-openapi-validator/blob/e934e372e9aab4deafaa2d3223cd1cb161848e44/src/middlewares/openapi.request.validator.2.ts#L160-L167

**Comment by cdimascio** [comment] 2019-07-19 17:50
@sheldhur fyi, that test now works
```
GET /v1/pets/my_id 400 1.286 ms - 102
      ✓ should return 400 when path param should be int, but instead is string
```

currently, its `bodyRequest` validation is not working.

**Comment by cdimascio** [comment] 2019-07-19 18:38
I figured out the request body stuff. It's now working. would be great if you could review. Are there additional cases to consider?

**Comment by cdimascio** [comment] 2019-07-19 18:38
in any case good progress:

```
  42 passing
  4 failing
```

**Comment by cdimascio** [comment] 2019-07-19 19:47
All tests are now passing
```
46 passing
```

@sheldhur please review the code. Assuming it looks good, perhaps I'll publish a beta release, so we get more testing

**Comment by richdouglasevans** [comment] 2019-07-19 19:56
Great work Carmine! Eager to use the fruit of your recent work 👍

**Comment by cdimascio** [comment] 2019-07-19 20:12
Huge thanks to @sheldhur! Much of my commit is based on his work. 
BTW, @sheldhur, I've added you to the repo as a collaborator

**Comment by cdimascio** [comment] 2019-07-20 12:10
@sheldhur @richdouglasevans v1.3.0-rc.3 is now available. it includes replaces the old request validator with the new. feel free to try it out and file issues if you into any issues

**Comment by richdouglasevans** [comment] 2019-07-20 13:17
Good work Carmine (and Sheldhur)

I"ve upgraded one of our API projects to use this latest version and can give the following feedback:

## The `$ref` support is improved

Previously there was an issue with validating `$ref`-erences. As a workaround until it was fixed we inlined a few of the types — thus incurring some duplication — and it worked fine.

Upgrading to `1.3.0-rc.3` has allowed me to remove the inlining and go back to nice DRY `$ref`-erences.

## Error messages have changed

We have tests that exercise validation: I had to change some of these because the error messages reported by `express-openapi-validator` changed.

> We do some transformation of the validation errors returned by the validator but we do just pass along some of the useful stuff such as the `path` and the `message` unchanged. 

### Finer-grained `path` reporting

For example, one of our tests sent a product (JSON) in the request body with an (invalid) negative price.

Previously we"d get this response:

```json
errors: [
    {
        "path": "items[0].price",
        "message": "Must be >= 0"
    }
]
```

And now we get this response: the `path` now is explicit about the error being in the body of the request.

```json
errors: [
    {
        "path": ".body.items[0].price",
        "message": "Must be >= 0"
    }
]
```

### Unsupported Media type message changed

`Unsupported Content-Type text/plain` :arrow_right: `unsupported media type text/plain`

### Richer `format` support

This snippet from our API spec mentions the `format`:

```yaml
quantity:
  type: integer
  format: int32
  minimum: 1
```

Previously, a test that sent an invalid float value for the `quantity` would result in this response:

```json
errors: [
    {
        "path": "items[0].quantity",
        "message": "Must be integer"
    }
]
```

Now we get this response which mentions the `format`:

```json
errors: [
    {
        "path": ".body.items[0].quantity",
        "message": "Must be integer"
    },
    {
        "path": ".body.items[0].quantity",
        "message": "Must match format \"int32\""
    }
]
```

**Comment by cdimascio** [comment] 2019-07-20 13:27
Thanks @richdouglasevans! Overall, this sounds very positive. I hope the error message changes did not cause too much pain.

**Comment by richdouglasevans** [comment] 2019-07-20 13:32
All good, I changed 'em very quickly and we're back to all green tests ✅ 

Cheers for this great project, it's proving very helpful to us.

**Comment by cdimascio** [comment] 2019-07-20 13:42
Fantastic to hear!

**Comment by cdimascio** [comment] 2019-07-20 13:42
closing this out. Opened the following to remove the remaining openapi-* deps
https://github.com/cdimascio/express-openapi-validator/issues/22

**Closed by cdimascio** 2019-07-20 13:42 UTC
Labels: enhancement

**Comment by sheldhur** [comment] 2019-07-20 14:02
@cdimascio @richdouglasevans there is one more minor feature associated with a stricter fit to the described scheme which `may affect safety` on projects in production. If I understand correctly,
`openapi-request-validator` filtering request fields what not described in scheme. Now you need to clearly indicate in schema what you want filtering fields that not described in schema. For this you need to add in the description of each schema field `additionalProperties: false`

@richdouglasevans I advise you to add this to the tests. 
 
https://github.com/epoberezkin/ajv#filtering-data
