### ISSUE TITLE
Validation failure

### ISSUE THREAD

**Issue by tumkurrunner** [cdimascio/express-openapi-validator#341] opened 2020-07-24 11:16 UTC
**Description:**
Problem using  Inheritance model
I have a base type Activity and Subtypes SubActivity1 SubActivity2 & SubActivity3 with discriminator propertyName set correct but still I get an error request should match exactly one schema in oneOf. Just to make if the spec is valid I tried https://bitbucket.org/atlassian/swagger-request-validator/src and validation is successful.

I have added the test yaml for reference.
```
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8086'
    description: Generated server url
paths:
  /test/api1:
    post:
      tags:
        - test-controller
      summary: Find something
      description: Do work
      operationId: getDecision
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/DecisionRequestDocument'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/DecisionResponseDocument'
components:
  schemas:
    DecisionResponse:
      required:
        - executionTimestamp
      type: object
      properties:
        name:
          maxLength: 50
          minLength: 1
          pattern: '^([ -$&-9:;=@-Z\x5e-z¡-£\xC0-\uFFFD]){1,50}$'
          type: string
          description: test name
        version:
          maxLength: 50
          minLength: 1
          pattern: '^([ -$&-9:;=@-Z\x5e-z¡-£\xC0-\uFFFD]){1,50}$'
          type: string
          description: version desc
        executionTimestamp:
          type: string
          description: RFC3339 format.
          format: date-time
          example: 2018-05-19T10:23:00.000Z
    DecisionResponseDocument:
      required:
        - data
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DecisionResponseResourceObject'
    DecisionResponseResourceObject:
      required:
        - attributes
        - type
      type: object
      properties:
        type:
          maxLength: 240
          minLength: 1
          pattern: '^[a-zA-Z0-9\-\.\s]{1,240}$'
          type: string
        attributes:
          $ref: '#/components/schemas/DecisionResponse'
        id:
          maxLength: 36
          minLength: 36
          pattern: >-
            ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
          type: string
    DecisionDetails:
      required:
        - decisionAdvice
      type: object
      properties:
        decisionAdvice:
          type: string
          description: Decide
          enum:
            - APPROVED
            - DECLINED
      description: test details
    TRY_ACTIVATION:
      required:
        - timestamp
        - type
      type: object
      description: Try activation activity
      allOf:
        - $ref: '#/components/schemas/Activity'
    Activity:
      required:
        - timestamp
        - type
      type: object
      properties:
        type:
          type: string
          enum:
            - PURCHASE
            - TRY_ACTIVATION
            - LOGIN
        timestamp:
          type: string
          description: RFC3339 format.
          format: date-time
          example: 2018-05-19T10:23:00.000Z
        accountId:
          maxLength: 20
          minLength: 1
          pattern: '^[0-9]{1,10}$'
          type: string
      description: The base type for an activity
      discriminator:
        propertyName: type
        mapping:
          PURCHASE: '#/components/schemas/PURCHASE'
          LOGIN: '#/components/schemas/LOGIN'
          TRY_ACTIVATION: '#/components/schemas/TRY_ACTIVATION'
    DecisionRequest:
      required:
        - activity
        - actor
      type: object
      properties:
        activity:
          oneOf:
            - $ref: '#/components/schemas/PURCHASE'
            - $ref: '#/components/schemas/LOGIN'
            - $ref: '#/components/schemas/TRY_ACTIVATION'
    DecisionRequestDocument:
      required:
        - data
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DecisionRequestResourceObject'
    DecisionRequestResourceObject:
      required:
        - attributes
        - type
      type: object
      properties:
        type:
          maxLength: 240
          minLength: 1
          pattern: '^[a-zA-Z0-9\-\.\s]{1,240}$'
          type: string
        attributes:
          $ref: '#/components/schemas/DecisionRequest'
        id:
          maxLength: 36
          minLength: 36
          pattern: >-
            ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
          type: string
    LOGIN:
      required:
        - password
        - timestamp
        - type
        - username
      type: object
      description: Login activity
      allOf:
        - $ref: '#/components/schemas/Activity'
        - type: object
          properties:
            username:
              maxLength: 30
              minLength: 6
              pattern: '^([ -$&-9:;=@-Z\x5e-z¡-£\xC0-\uFFFD]){1,50}$'
              type: string
              description: Username for online account access
            password:
              pattern: '^([ -$&-9:;=@-Z\x5e-z¡-£\xC0-\uFFFD]){1,50}$'
              type: string
              description: Password for online account access
    PURCHASE:
      required:
        - cost
        - testname
        - reference
        - timestamp
        - type
      type: object
      description: online purchase activity
      allOf:
        - $ref: '#/components/schemas/Activity'
        - type: object
          properties:
            testname:
              maxLength: 100
              minLength: 1
              pattern: '^((?![~%:;?<>\[\]{}|^\\])[\s\S]){1,100}$'
              type: string
            reference:
              maxLength: 50
              minLength: 1
              pattern: '^[A-Za-z0-9-_]{1,50}$'
              type: string
            cost:
              type: object
              properties:
                amount:
                  type: number
                currency:
                  type: string
```

**Comment by cdimascio** [comment] 2020-08-14 00:21
@tumkurrunner can you provide the example request 
also, i see that the `DecisionRequest` requires `actor`, but actor is not defined as a property anywhere. 

it would be good to solve these issues first i.e. that one noted above. also, it will be great if you can provide a canonical version of this spec with the minimum to reveal the error. it will certainly help to make the investigation simpler.

**Comment by GiriMPT** [comment] 2020-08-14 13:15
Don't worry I found a work around, I got the answer from here https://github.com/OAI/OpenAPI-Specification/issues/2141#issuecomment-650200324.

**Comment by cdimascio** [comment] 2020-11-15 20:14
@tumkurrunner i'm working on an initial version of discriminator support. it will start by supporting top level types. will expand it to this use case. #461

**Comment by cdimascio** [comment] 2024-01-28 17:23
Closing as it is a Duplicate of the following https://github.com/cdimascio/express-openapi-validator/issues/104

Additionally, top level (not full discriminator) discriminator support exist exists https://github.com/cdimascio/express-openapi-validator/pull/461

**Closed by cdimascio** 2024-01-28 17:23 UTC
