### ISSUE TITLE
Support for OpenAPI 3.1.0

### ISSUE THREAD

**Issue by harryc9** [cdimascio/express-openapi-validator#755] opened 2022-09-08 04:04 UTC
Hi, are there plans to support OpenAPI 3.1.0 with this library?

We're currently running into issues when validating the API spec because Stoplight API exports are using features exclusive to 3.1.0. Mainly trying to avoid workarounds where we manually downgrade the OA version and remove the said block post-export.

The specific feature being a change to the `Schema` [definition](https://spec.openapis.org/oas/v3.1.0#fixed-fields-19) to contain `examples`

```
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 0
          firstName: Bob
          lastName: Ross
          email: bob@example.com
          emailVerified: true
          createTime: '2019-08-24T12:42:12Z'
          lastUpdateTime: '2020-09-23T08:17:41Z'
``` 

Thank you!

**Comment by nd-jharn** [comment] 2022-10-17 11:51
It seems they have done the work, but have not yet released it as an update:
https://github.com/cdimascio/express-openapi-validator/pull/713

**Comment by OlivierCuyp** [comment] 2022-11-15 18:13
@essential-randomness would it possible to have a version that works without $dynamicAnchor and $recursiveAnchor ?
With a big warning on the main page about this ?
I'm missing so much `null` type and `unevaluatedProperties` for composition with allOf.

**Comment by essential-randomness** [comment] 2022-11-15 19:03
Ah, man, I wish. There may be some movement on the AJV issue since yesterday, and if I understand correctly they offered a bounty. As far as my exploration went, I don't think it's possible to do anything about this without the AJV issue being resolved.

**Comment by OlivierCuyp** [comment] 2022-11-16 09:24
@essential-randomness sorry, I didn't dig into the implication of $dynamicAnchor and $recursiveAnchor.
I was just hoping it was ad hoc features...
And yes, I saw this 500-1000$ bounty. Hopefully it will create some movement around this AJV issue.
It is so sad, OpenApi 3.1 has exactly all the features needed to do good composition and type validation.

**Comment by OlivierCuyp** [comment] 2022-11-18 22:51
@essential-randomness I'm really curious, it seems that **fastify-openapi-glue** succeed to have the openapi 3.1.0 specification working:
https://github.com/seriousme/fastify-openapi-glue/issues/178

To be honest I didn't test it but according to some colleagues, it works well.
Maybe they found a valid workaround.

**Comment by essential-randomness** [comment] 2022-11-18 23:05
From there:

>  3.1, by converting $dynamicRef and $dynamicAnchor into $ref and $anchor for now. This might cause some limitations for now but I think thats worth it.

I have no idea of the implications of this, nor would know what this conversion entails, but this is how they seem to be doing it.

**Comment by nexsodev** [comment] 2023-05-17 12:47
Still nothing?

**Comment by lhimstedt** [comment] 2023-05-23 07:18
It would be cool to have features like unevaluatedProperties from draft 2019-9. I tried to change the draft, but I may need to spend more time if nothing happens on this issue.

**Comment by Jackman3005** [comment] 2023-12-26 22:58
I think this is a duplicate of [this issue](https://github.com/cdimascio/express-openapi-validator/issues/573).

**Comment by Jackman3005** [comment] 2023-12-26 22:59
As I [posted about on the above issue](https://github.com/cdimascio/express-openapi-validator/issues/573#issuecomment-1869810476), is it possible for this library to take on the preprocess step to resolve $dynamicRef before calling out to AJV? If not, would it be possible to provide a solid reason why it belongs in AJV to respond and continue pushing this forward?

**Comment by thernstig** [comment] 2023-12-27 13:26
This is a duplicate of https://github.com/cdimascio/express-openapi-validator/issues/573

**Comment by cdimascio** [comment] 2024-08-24 15:45
Closing this in favor of the duplicate: https://github.com/cdimascio/express-openapi-validator/issues/573

**Closed by cdimascio** 2024-08-24 15:45 UTC
