### ISSUE TITLE
how ignorePaths work?

### ISSUE THREAD

**Issue by mirekgw** [cdimascio/express-openapi-validator#245] opened 2020-02-25 18:26 UTC
I'm trying to **not** validate request data for specific path and I was trying to use ignorePaths, but it seems it's not working as I tough.

I have a path in openapi .yaml file that I would like to exclude from body verification. But I would still like to use param parsing that openapi validator is doing (in `applyOpenApiMetadata` function).

I'm seeing when request is processed that `lookupRoute()` in `applyOpenApiMetadata()` is matching my request and code never goes into `openApiContext.isManagedRoute`, and that is the only place where `ignorePaths ` is used.

My assumption is that fix for this problem may be that `ignorePaths` property is checked in `buildMiddleware()` or maybe in `validate()` function in openapi.request.validator.js

Could you please explain how ignorePaths should work as documentation is very brief.
Thanks

**Comment by cdimascio** [comment] 2020-02-25 22:40
thanks @mirekgw , just checked the code`ignorePaths` is broken. the test cases are also broken and incorrectly pass. we'll have a look.

**Comment by cdimascio** [comment] 2020-02-25 23:03
should have a fix soon see #247 
in terms of intended behavior... provide a regex to `ignorePaths`. Path matched by the regex will be ignored.

**Comment by cdimascio** [comment] 2020-02-25 23:05
fix is in `v3.9.1`

**Comment by cdimascio** [comment] 2020-02-27 18:19
@mirekgw did you have success with the fix? Note, i also made some updates to the README.

**Closed by cdimascio** 2020-02-27 18:19 UTC
Labels: bug
